- op-node-derivers.md
Design doc for refactor of the Driver/Derivation in op-node, and introduction of "Deriver" to make the core chain validation processes of the rollup-node more extensible. This supports new projects such as interop by providing cleaner abstractions for major new functionality.
> Add `op-node-derivers` design doc

- README.md
Create some simple instructions for enable devs to
schedule design review sessions. The schedule lives
on Github and the process involves commenting on the
github issue that corresponds to the design review
session that you would like to have your design
doc reviewed in.
> readme: simple instructions for session inclusion

- README.md
Updates the readme to make the process around the public design
docs repo more clear. This mosly backports an internal document
to being public.
> design-review: update readme

- protocol/interoperable-ether.md
Adds a design doc for what interoperable ether. This is a core feature for interop devnet v2.
The `ISuperchainERC20` spec can be found [here](https://github.com/ethereum-optimism/specs/pull/71)
> design-doc: interoperable ether

- protocol/invalid-block-progression.md
A design doc describing the two invariants that can ensure
that the derivation pipeline can always progress without needing
to stall and do a lot of extra work when invalid batches are submitted.
Ideally this can be included in a hardfork before interop ships
to make the derivation pipeline much more hardened for interop.
> design doc: invalid block progression

- protocol/superchainerc20/convert.md
This document presents a solution for migrating `OptimismMintableERC20`, which corresponds to locked liquidity in L1, to the `SuperchainERC20` standard to be interop compatible.
To do that, we suggest using the `L2StandardBridge` mint/burn rights over the legacy representations to allow easy conversion between the `OptimismMintableERC20` and the corresponding `SuperchainERC20`.
In contrast to the isolated approach presented here https://github.com/ethereum-optimism/design-docs/pull/45, this PR focuses on the unified approach, where multiple legacy tokens can be converted into one single `SuperchainERC20`.
> design-doc: convert-unified

- ecosystem/opUSDC/op-usdc.md
This PR adds the OpUSDC design doc.
The document proposes a solution for implementing the bridged USDC standard that can be easily upgraded to native USDC. This solution accomplishes the Circle requirements and accommodates OP Stack specifications to allow Chain Operators to perform an easy and secure migration in agreement with Circle.
- We are currently working on the repo, and it will be made public soon
Any feedback is welcomed.
> design-doc: opUSDC

- ecosystem/supersim.md
Design document for supersim, a local multichain development environment for app developers building on the Superchain.
> design-doc: supersim

- protocol/superc20/liquidity-migration.md
Added a design doc file discussing the possible approaches for the liquidity migration process for tokens locked in L1, deployed through the current and legacy `OptimismMintableERC20` Factories in L2 (also known as _legacy tokens_), to make them fungible and compatible with Superchain interoperability.
> design-doc: liquidity migration

- protocol/superchainerc20/L1-native-factory.md
- protocol/superchainerc20/SuperchainERC20-factory.md.md
This document presents the requirements for a factory that deploys `SuperchainERC20` tokens for tokens native to L1.
> design-doc: SuperchainERC20 Factory for L1 native tokens

- protocol/op-stack-manager-arch.md
This design doc details an architecture for OP Stack Manager that ideally fits the modular interop use case expressed in #52 that we move towards in https://github.com/ethereum-optimism/optimism/pull/11189.  It focuses on L1 contracts only. Our current deploy config and deploy script is a monolith, so here we break it up into 3 discrete steps, each with their own distinct inputs and outputs.
> OP Stack Manager architecture to support interop

- protocol/forge-scripts-deploy-in-go.md
This introduces the idea of running the Forge scripts, primarily the chain deployment / genesis setup scripts, in Go.
This improves the integration with Go tooling and tests, to unlock the customization we need for things like Interop, and to generally improve test coverage of our deployments.
**Metadata**
Fix https://github.com/ethereum-optimism/optimism/issues/11360
> protocol: forge scripts deploy in Go

- assets/design-doc-template.md
Turn the design-doc guide / hints into HTML comments, and split nicely over multiple lines.
These don't render in the markdown, so now the writer can keep them around while writing their doc.
> assets: apply comments to design doc guide/hints

- ecosystem/op-deployer.md
- protocol/forge-scripts-deploy-in-go.md
- protocol/op-contracts-manager-arch.md
This is part of a broad rename of OPStackManager to OPContractsManager. 
Related PR: https://github.com/ethereum-optimism/optimism/pull/12091
> rename: OpStackManager -> OPContractsManager

- protocol/superchainerc20/superc20Redesign.md
We introduce a design doc to discuss a design change in the `SuperchainERC20` standard, as described in the [interop specs](https://github.com/ethereum-optimism/specs/blob/main/specs/interop/token-bridging.md). The goal of this PR is to open the discussion and ensure we are on the best possible path.
> interop: added superc20Redesign design doc

- solidity/solc-update-0.8.15-to-0.8.25.md
This covers solidity version upgrade of all OP Stack smart contracts from 0.8.15 code to 0.8.25.
Fixes https://github.com/ethereum-optimism/optimism/issues/11527
> OP Stack SOLC update from 0.8.15 to 0.8.25

- protocol/holocene-derivation.md
- protocol/strict-derivation.md
Holocene design doc, to align on open questions.
After getting alignment, the specs can be completed. They are currently in draft at https://github.com/ethereum-optimism/specs/pull/357
This has been reviewed in a public design review session on 2024-09-11, with a [public recording](https://discord.com/channels/1244729134312198194/1283534070252568636/1283692806094983199).
> Add Holocene design doc

- protocol/opcm-test-integration.md
Outlines an approach to integrating the OPCM into the `Deploy.s.sol` script used in the forge test suite.
> Add opcm test integration

- security/fma-superchainerc20-standard.md
This PR introduces the FMA for the `SuperchainERC20` standard. 
It will allow the use of the `SuperchainERC20` standard without requiring interop functionalities to be enabled at that time.
> feat: Add FMA superchainerc20 standard

- security/fma-superchainerc20-standard.md
Reflecting a name change, updating the predeploy contract from `SuperchainERC20Bridge` to `SuperchainTokenBridge`.
> update: fma superchainerc20

- protocol/external-block-production.md
This document proposes a sidecar to `op-node` for requesting block production from an external party.
**Tests**
No tests have been added, but the Software Maintenance section details a path to incorporating in standard OP Stack e2e testing after an initial trial.
By decoupling the block construction process from the Sequencer's Execution Engine, operators can tailor transaction sequencing rules without diverging from the standard Optimism Protocol Client. This flexibility allows individual chains to experiment on seqeuncing features, providing a means for differentiation. This minimum viable design also includes a local block production fallback as a training wheel to ensure liveness and network performance in the event of local Block Builder …
> External Block Production Sidecar

- security/fma-superchainerc20-standard.md
Reflecting changes in the specs, which removes __ from `SuperchainERC20` crosschain functions.
> update: superchainerc20 changes

- protocol/superchain-erc20/storage-upgrade.md
Issue: [#11602](https://github.com/ethereum-optimism/optimism/issues/11602)
This document discusses two different approaches to perform the one time storage update of `OptimismMintableERC20Factory` necessary to include tokens deployed before holocene into the `deployments` mapping. It also provides implementation details.
> interop: OptimismMintableERC20Factory storage update

- cannon-state-versioning.md
Proposal for handling changes to the offchain Cannon STF.
> Cannon state versioning

- security/DeputyGuardianModule-Proxy.md
Introduce a proposal that will prevent to regenerate the PSPs and make some unnecessary changes to the guardian contract each time we update the `DeputyGuardianModule` code. 
As discussed [here on discord.](https://discord.com/channels/1244729134312198194/1278362089597046846/1286684655407464498)
>  Change `DeputyGuardianModule` to use a Proxy to be `DeputyGuardianModuleProxy`

- security/op-node-op-signer-integration.md
This PR introduces how we can integrate op-node with op-signer when signing the block payload for sequencer gossiping.
> feat: Integrate op-node with op-signer for block payload signing

- protocol/proofs/withdrawal-invalidation-mitigation.md
Introduces a proposal that would prevent user withdrawals in the OptimismPortal from being invalidated any time that the fallback is utilized.
> feat: OptimismPortal wd invalidation mitigation

- protocol/proofs/delayed-weth-expansion.md
Introduces a proposal to improve some of the incident response capabilities present in the DelayedWETH contract.
> feat: improve DelayedWETH response capabilities

- protocol/proofs/fdg-refund-mode.md
Proposes a change to the FaultDisputeGame that allows it to automatically enter a "refund mode" when the game finds itself to be blacklisted.
> feat(proofs): FaultDisputeGame refund mode

- security/fma-generic-contracts.md
Introduces an `fma-generic-contracts.md` document in the `security` directory covering contract upgrades.
This was asked for by @mds1 as part of Stage 1.4 FMA review in https://github.com/ethereum-optimism/design-docs/pull/132.
These generic items were ported from [notion](https://www.notion.so/oplabs/MCP-L1-PRs-Overview-Failure-Modes-and-Recovery-Path-Analysis-d81b84dd1fd8458f9e81de74897726fe?pvs=4).
> feat: fma-generic-contracts

- protocol/move-cannon-and-dispute-folders-to-L1-folder.md
This design doc proposes moving the Cannon and Dispute contracts into the L1 folder since they are actually L1 contracts.
Issue: https://github.com/ethereum-optimism/optimism/issues/12643
> Proposal to reorganize OP Stack contracts folder structure

- solidity/revert-strings-to-custom-error-migration.md
Set a clear standard on how to handle errors for OP Smart Contracts, using only custom errors and reverts.
**Tests**
No tests needed
Carried over from discord, but the idea is to stop bikeshedding around using both require with error strings and custom errors and just standardized on custom errors, which I lay out in the doc. There was some concern around using require in scripts + tests, but after some discussion on discord we agreed `assertEq` should be able to cover that in most cases
**Metadata**
[optimism issue #12478](https://github.com/ethereum-optimism/optimism/issues/12478)
> Standardize on Custom errors

- protocol/remove-l2oo.md
Design doc to agree on a strategy to allow us to remove the pre-fault proof code such as L2OutputOracle.
> Remove legacy `OptimismPortal` and `L2OutputOracle` contracts

- protocol/op-contracts-manager-arch-redesign.md
- protocol/op-contracts-manager-single-release-redesign.md
OPCM requires a redesign based on recent conversations highlighting the need for upgrade functionality. This design doc is preemtively making some changes to make introducing upgradability features to OPCM easier.
Ongoing discussions happening in Optimism R&D [discord](https://discord.com/channels/1244729134312198194/1273519241076670526).
> opcm-redesign: Rearchitecting OPCM to handle only one L1 smart version release

- protocol/interoperable-ether.md
- protocol/op-node-derivers.md
- protocol/proofs/fdg-refund-mode.md
- protocol/standard-l2-genesis.md
- security/fma-fjord.md
- security/fma-generic-hardfork.md
- security/fma-holocene.md
Corrected "accomodate" to "accommodate".
Corrected "proceses" to "processes".
Corrected "cand" to "can".
Corrected "here" to "hear".
Corrected "registy" to "registry" and much more.
This pull request contains changes to improve clarity, correctness and structure. Please review the changes and let me know if any additional changes are needed.
> typo correction in documentation files

- protocol/eth-shared-lockbox.md
Co-authored-by: ng <ng@defi.sucks>, agusduha <agusduha@defi.sucks>
The following design doc cover a previous discussed issue on [ETH withdrawals](https://github.com/ethereum-optimism/specs/issues/362) introduced by interop. The Shared lockbox is presented as the most convenient solution to solve this problem. However, it is known that the design also is the interest for various aspects of the Superchain design, such as chain management, core interop, and others, which need to be carefully discussed.
This doesn't address the case for L1 bridged tokens.
> interop: add Dependency Set Manager & Shared Lockbox design doc

- protocol/l1-upgrades.md
Describes a fully onchain upgrade process.
> OPCM L1 Upgrades

- protocol/interoperable-ether-transfers.md
This PR introduces a design for simplifying `ETH` transfers between two interoperable L2 chains by reducing the process from four transactions to two. The new approach leverages the `SuperchainWETH` contract, which now includes two new functions: `sendETH` and `relayETH`. 
- **`sendETH`**: Deposits `ETH` in the `ETHLiquidity` contract and sends a message to the destination chain, encoding the relay details.
- **`relayETH`**: Withdraws the specified amount of `ETH` from `ETHLiquidity` on the destination chain and transfers it to the recipient.
This update streamlines L2-to-L2 `ETH` transfers, bypassing the need for separate wrapping and unwrapping steps. Notably, custom gas token chains are excluded from this simplification to maintain compatibility and reduce risk.
- **Pros**: Simplifies …
> interop: interoperable ether transfers design doc

- protocol/l1-upgrades.md
Clarifying that we cannot use the `pure` keyword for the OPCM upgrade function. Additionally, fixed some small nits.
> Cannot use pure keyword for OPCM upgrade function

- protocol/proofs/pdg-no-proposer-play.md
Proposes a change to the PermissionedDisputeGame such that the Proposer will no longer be allowed to play the game. Instead, only the Challenger will be allowed to play the game. This more clearly mirrors the behavior of the L2OutputOracle.
> feat: only allow challenger to play permissioned game

- protocol/op-contracts-manager-single-release-redesign.md
This PR makes the naming consistent with the code [here](https://github.com/ethereum-optimism/optimism/blob/d784a98b34e28866b4ddbe2f46fb0b59ce95e6ba/packages/contracts-bedrock/src/L1/OPContractsManager.sol#L132).
> rename `l1ContractsVersion` to `l1ContractsRelease`

- security/fma-l1-upgrades.md
FMA associated with [OPCM Upgrades](https://github.com/ethereum-optimism/design-docs/blob/main/protocol/l1-upgrades.md).
> feat: Add OPCM upgrades FMA

- protocol/consensus-nonces.md
Add a design doc for the consensus nonce tracking design outlined in https://github.com/ethereum-optimism/specs/issues/330#issuecomment-2354217166.
**Tests**
N/A
Tracking doc here: https://github.com/ethereum-optimism/optimism/issues/13543
> Add design doc for consensus event nonce tracking

- protocol/deprecate-reqresp-sync.md
This design-doc proposes to deprecate the request-response sync mode, in favor of EL-sync.
This design-doc also suggests a way to tweak the gossip relay rules, so we can provide a sync-target to nodes more reliably.
The choice of deprecating request-response sync is based on discussion with @sebastianst about ways we can improve the op-node sync reliability.
> protocol: deprecate reqresp sync

- protocol/test-sequencing.md
This design-doc introduces the idea of building a test service for sequencing, to help cover the many tx-inclusion and reorg cases in the interop test plan. Later, we can potentially build it out into a production sequencer, standalone from the op-node.
> protocol: test-sequencing service

- security/fma-superchainweth.md
This PR introduces the FMA for the SuperchainWETH design.
Below are the references for this project:
- Design docs: [intro](https://github.com/ethereum-optimism/design-docs/blob/main/protocol/interoperable-ether.md), [transfer feature](https://github.com/ethereum-optimism/design-docs/blob/main/protocol/interoperable-ether-transfers.md).
- [Specs](https://github.com/ethereum-optimism/specs/blob/main/specs/interop/superchain-weth.md).
- Implementation: [SuperchainWETH](https://github.com/ethereum-optimism/specs/blob/main/specs/interop/superchain-weth.md), [ETHLiquidity](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L2/ETHLiquidity.sol).
Note that failures upon which SuperchainWETH depends will be covered in a …
> feat: Add FMA SuperchainWETH

- security/fma-ban-deposits.md
This PR introduces the FMA for the deposit context feature, in order to ban `ExecutingMessage` deposits.
Below are the references for this project:
- Contracts and client updates are documented [here](https://github.com/ethereum-optimism/specs/pull/258).
- Implementation and tests are found [here](https://github.com/ethereum-optimism/optimism/pull/11712).
> feat: add fma ban deposits

- security/fma-shared-lockbox.md
This PR introduces the FMA for the new Shared Lockbox design.
Below are the references for this project:
- [Specs PR](https://github.com/ethereum-optimism/specs/pull/465).
- [Implementation PR](https://github.com/ethereum-optimism/optimism/pull/13144)
It replaces the previous FMA, which can be found [here](https://github.com/ethereum-optimism/design-docs/pull/180) for reference.
> feat: Add new FMA Shared Lockbox

- security/fma-incident-response-improvements.md
Here we add an FMA for the proofs incident response changes from https://github.com/ethereum-optimism/optimism/issues/12172
> feat: add FMA for proofs incident response improvements 

- protocol/proofs/generic-withdrawal-proofs.md
Introduces a proposal to include super root validation logic inside of the base optimism portal contract.
> feat: super root withdrawal proofs

- protocol/eth-shared-lockbox.md
Making changes to the current ETH lockbox design doc to apply the new design changes. The dependency set is removed from L1 and the `SuperchainConfig` is no more related with the lockbox. Every portal will migrate to have its own lockbox and later two lockboxes can be merged. We use the "upgrader controller" as the authorized role instead of the system admin to be coordinated with the new OPCM design.
> feat: ETH lockbox redesign

- protocol/proofs/interop-config.md
Design doc to review options to ensure the split depth is suitable for interop games.
> Add design doc for interop game config

- security/fma-multi-threaded-64-bit-cannon.md
This is the failure modes analysis for multi-threaded & 64-bit Cannon.
> fma: FMA for MT/64-bit Cannon

- protocol/interop-access-list.md
This design introduces a new validation mechanism for cross-chain message execution using transaction access-lists. The `CrossL2Inbox` contract will implement gas introspection to validate `ExecutingMessage` transactions. Each cross-chain message must be pre-declared in the transaction's access list.
Co-authored-by: @skeletor-spaceman @0xng @tynes @protolambda
> feat: add interop access list

- assets/fma-template.md
Link to the audits process in the SDLC, instead of the previous framework (parts of which are still used, but from within audits in the SDLC).
> feat: add link to the SDLC from the FMA template to continue into audits

- protocol/interop-topology.md
Design doc that is meant to define clearly the topology for a cloud
deployment of an OP Stack cluster. This is not meant to define the
only way to deploy a cluster, but is the architecture that we will
do our security review against to ensure that it is not possible to
attack a cluster.
> interop: Topology and Tx Flow for Interop Chain Operation

- security/fma-ban-deposits.md
This commit deprecates the FMA associated with the deposit context, as
well as linking to the new design.
Closes https://github.com/ethereum-optimism/optimism/issues/11676
> design-docs: deprecate the deposit context

- protocol/resend-messages.md
Introducing a new `resendMessage` to re-emit the `SentMessage` event for a message that was never relayed and became very old for the supervisor to pick it up.
**Metadata**
* [issue](https://github.com/ethereum-optimism/optimism/issues/15284)
* [spec](https://github.com/ethereum-optimism/specs/pull/659)
* [implementation](https://github.com/ethereum-optimism/optimism/pull/15300)
> feat: resend message

- security/fma-superchainerc20.md
Add corresponding tests to FMA
**Metadata**
Issue: https://github.com/ethereum-optimism/design-docs/issues/235
> fix: superchain erc20 FMA

- ecosystem/l2tol2cdm-relayedmessage-return.md
Increase leverage of the L2ToL2CDM by including the return value in the RelayedMessage event
> feat: l2tol2cdm RelayedMessage return value

- security/fma-superchainethbridge.md
Finalize `SuperchainETHBridge` FMA and add tracking monitoring issue
**Metadata**
Issue: https://github.com/ethereum-optimism/design-docs/issues/234
> feat: finalize superchain eth bridge FMA

- security/fma-message-passing-contracts.md
Finalize Msg Passing FMA and add tracking monitoring issue
**Metadata**
Issue: https://github.com/ethereum-optimism/design-docs/issues/237
> fix: finalize Msg Passing FMA

- security/fma-interop-access-list.md
Adds Failure Modes and Recovery Path Analysis (FMA) for the Interop Access List mechanism. 
FMs:
- Gas Introspection Breaks Due to EVM Changes or Compiler Optimizations
- Storage slot collisions
- Unexpected Storage Slot Warming Behavior
- Design PR: https://github.com/ethereum-optimism/design-docs/pull/214
- Specs PR: https://github.com/ethereum-optimism/specs/pull/612
**Metadata**
Issue: https://github.com/ethereum-optimism/design-docs/issues/238
> feat: add interop access list FMA

- security/fma-supervisor.md
Failure Mode Analysis for `op-supervisor`, a new consensus-critical piece of code for the op-stack.
> FMA: OP-Supervisor

- assets/design-doc-template.md
Fixes a syntax error in an html comment closing tag that causes the next markdown section to be considered part of the comment.
> Fix broken comment syntax

- security/fma-stage-1.md
FMA for the stage 1 changes, tracking issue with specs, design-doc and implementation: https://github.com/ethereum-optimism/optimism/issues/15075
> start stage 1 fma draft

- protocol/interop-monitoring.md
Monitoring service is a critical service for detecting and responding to potential invalid messages across the superchain.
> design doc: interop monitoring

- README.md
We use doctoc for maintaining tables of contents. This explains how.
> Add doctoc instructions to README.

- protocol/decoupled-features.md
This PR replaces #297.
Instead of making changes to the `superchain-registry` like #297, this PR
proposes that features are decoupled at the client side such that clients
may choose how to toggle features on and off. It avoids adding features to
the superchain registry which can be considered non-customizable chain
configuration values once they are committed to a hardfork in the OP Stack.
This PR outlines two ways to implement the client-side decoupling of
features from hardforks based on the discussion in #297. It also lists
the superchain-registry decoupling method in #297 as a considered
alternative, with a more complete description of that alternative
in #297.
> feat(protocol): Feature Decoupling V2

- protocol/operator-fee-scalar-fix.md
This is the current operator fee formula.
```
operatorFee = operatorFeeConstant + operatorFeeScalar * gasUsed / 1e6
```
The `1e-6` multiplier on the `operatorFeeScalar` is not useful for operators as it results in a fee that is too low to be useful. This design doc proposes the following change to the operator fee formula.
```
operatorFee = operatorFeeConstant + operatorFeeScalar * gasUsed * 10
```
With the new fee formula, here are some examples of some possible fees being charged. 
For the dollar cost column, we assume an ETH price of 2.5k.
| Gas Used | `operatorFeeScalar` | `operatorFeeScalar * gasUsed * 100` | Dollar Cost |
|----------|-------------------|----------------------------------|-------------|
| 30,000,000 | 1 | 3 gwei | $0.0000075 |
| 30,000,000 | 2^32 | 1.29e10 gwei | …
> feat: operator fee scalar fix

- security/fma-minimum-base-fee.md
See updated spec https://specs.optimism.io/protocol/jovian/exec-engine.html#minimum-base-fee-in-block-header (we changed the design from 1 byte to 8 bytes).
> min-base-fee FMA: update calculation for DB growth

- safe-modules/liveness-module-v2.md
This PR includes a design document that proposes an updated LivenessModule to be installed into all safes managed by OP Labs and the Optimism Foundation, and potentially the Security Council.
> feat: liveness module v2
