plasma-mode.md

This adds the design doc for plasma mode.
**Metadata**
- Fixes https://github.com/ethereum-optimism/client-pod/issues/830

Add Plasma Mode Design Doc

---

op-node-derivers.md

Implement changes based on what was aligned on in the call:
- Implement event-emitter proposal that addresses review feedback from Adrian.
- Add phase 1b, to make map out the event processing, before proceeding to phase 2.

op-node-derivers: update with design-review call feedback

---

assets/fma-template.md
security/failure-modes-analysis.md

- Adds a `security/` folder to document security processes
- The design doc is `security/failure-modes-analysis.md`
- That design doc links to the FMA template in `assets/fma-template.md`

Add FMA design doc and template

---

smart-contract-feature-development.md

Outlines a proposal on how to do solidity smart contract
development in a way that reduces the need for feature
branches. We are testing this out in interop and it would
be nice to have the org on board with this as a pattern.

feat: solidity feature development

---

protocol/smart-contract-versioning.md

This design doc proposes a new smart contracts versioning scheme to improve clarity and more closely align with typical semantic versioning practices.

Changes to Monorepo and Contract Versionings

---

security/fma-fjord.md

Add metadata section, TOC, and two remaining failure modes (P256, setImplementation failure to execute)

Add metadata section, TOC, and last failure modes

---

assets/design-doc-template.md

Updates the template to include a section about resource usage.
This is important to consider with design docs because blockchain
is a systems engineering discipline and we need to be considerate
of the resource usage of our solutions.
Also move the alternative solutions to below the proposed solution.
This flow makes more sense when reading the document.

design-docs: update template

---

protocol/solidity-versioning.md

Proposes a process for Solidity version upgrades

feat: solidity versioning process

---

assets/solc-update-template.md

fix: remove summary section from solc template

---

README.md

Closes https://github.com/ethereum-optimism/design-docs/issues/91

design-review: add process

---

assets/solc-update-template.md

This adds a Table of Content, Header table and Action items to the solc-update-template

modify solc-update-template

---

security/fma-holocene.md

Holocene FMA: add section on configurable EIP-1559 params

---

security/fma-holocene.md

Holocene FMA: some formatting changes

---

security/fma-generic-hardfork.md
security/fma-superchainerc20-standard.md

* Adds information about detection of head stalls
* Rearranges and dedupes content around failure modes causing a chain split versus those that do not
* Adds action items, these are the main value of the FMA process.

generic fma: improve

---

protocol/proofs/anchor-state-poison-protection.md

Proposes a change to the AnchorStateRegistry that would resolve the poisoning problem.

feat: AnchorStateRegistry poisoning protection

---

security/fma-asterisc.md
security/fma-kona-asterisc.md

A failure modes and recovery paths analysis for Stage 1.4: Kona and Asterisc.
*Status:* **In Review**

feat: Stage 1.4: Kona + Asterisc FMA

---

security/fma-holocene.md

Just raising this draft as a place holder so we can track the actions which are being implemented and then mark the FMA as final. Do not merge yet.

holocene-fma: set status to final

---

protocol/deputy-pause-module.md

Proposes the DeputyPauseModule to be installed into the Foundation Safe.

feat: propose DeputyPauseModule

---

security/fma-generic-hardfork.md
security/fma-l1-pectra.md

Adds a Failure Modes Analysis for Upgrade 12 (L1 Pectra Readiness).

Add L1 pectra defense FMA

---

assets/design-doc-template.md

Updates the template to more explicitly display the DRI and reviewers.
This matches how the FMA template works.

design-docs: better template

---

assets/design-doc-template.md

We are moving the  FMAs to the design phase.
- FMAs can now be an input to implementation
- Audit procurement can start immediately after design review
The [SDLC](https://github.com/ethereum-optimism/pm/blob/main/src/sdlc.md) has been updated in its repo, along with a smoother [audit process](https://github.com/ethereum-optimism/pm/blob/main/src/audits.md). How the [FMA determines the audit requirements](https://github.com/ethereum-optimism/pm/blob/main/src/fmas.md) has also been updated.

Require a link to the FMA in the design docs

---

security/fma-generic-hardfork.md
security/fma-withdrawals-root-in-block-header.md

Adds an FMA for the "withdrawals root in block header" feature, planned for inclusion in the Isthmus hardfork.

FMA for withdrawals root in block header

---

security/fma-message-passing-contracts.md

Remove "Ban deposit" references

fix: Msg passing FMA

---

security/fma-interop-access-list.md

Finalize Interop Access List FMA after adding documentation and tests
Documentation PR: https://github.com/ethereum-optimism/specs/pull/664
Tests PR: https://github.com/ethereum-optimism/optimism/pull/15465
**Metadata**
Closes https://github.com/ethereum-optimism/design-docs/issues/238

feat: finalize access list FMA

---

protocol/standard-validator.md

Adds a proposal for StandardValidator improvements

Add Standard Validator update design doc

---

security/fma-interop-portal.md

Marks action items as complete, this is done now.

feat: finalize portal fma

---

protocol/decoupled-features.md

Small updates to follow up on #300, fixing typos + general cleaning.

fix(protocol): Feature Decoupling Followup Fixes

---

security/fma-minimum-base-fee.md

Closes https://github.com/ethereum-optimism/design-docs/issues/316

min-base-fee FMA: add estimate for DB growth
